version: "3.8"

services: 
  frontend:
    build: frontend
    ports: 
      - "80:80"
  backend:
    build: backend
    expose: 
      - 8080
    depends_on: 
      - database
  database:
    image: mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: ecommerce
    volumes: 
      - volume-test:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

secrets:
  db_root_password:
    file: ./db_root_password.txt
  db_password:
    file: ./db_root_password.txt

volumes: 
  volume-test: