version: "3.8"

services: 
  frontend:
    build: frontend
    ports: 
      - "80:80"
  backend:
    build: backend
    ports: 
      - "8080:8080"
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: ecommerce
    secrets:
      - db_root_password
      - db_password

secrets:
  db_root_password:
    file: ./db_root_password.txt
  db_password:
    file: ./db_root_password.txt
